config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :about
  resources :topics do
    resources :comments, :controller => 'topic_comments'
    resources :likes

    member do
      post :subscribe
      delete :unsubscribe
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true

  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :liked_topics, :through => :likes, :source => :user
  has_many :subscriptions, :dependent => :destroy
  has_many :subscribed_topics, :through => :subscriptions, :source => :user
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  belongs_to :category
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def find_my_like(user)
    if user
      self.likes.where(:user_id => user.id).first
    else
      nil
    end
  end

  def find_my_subscription(user)
    if user
      self.subscriptions.where(:user_id => user.id).first
    else
      nil
    end
  end

  def tag_list
    tags.map(&:name).join(',')
  end

  def tag_list=(tags)
    self.tag_ids = tags.split(',').map do |tag_name|
      tag_name = tag_name.strip.downcase
      tag = Tag.find_by_name(tag_name) || Tag.create(name: tag_name)
      tag.id
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_topic, only: [:show, :subscribe, :unsubscribe]
  before_action :find_my_topic, only: [:edit, :update, :destroy]

  def index
    case params[:order]
    when 'newest_post'
      @topics = Topic.order('created_at DESC')
    when 'most_replies'
      @topics = Topic.eager_load(:comments).group('topics.id').order('count(comments.topic_id) DESC')
    else
      @topics = Topic.all
    end

    if params[:category]
      @category = Category.find( params[:category] )
      @topics = @category.topics
    end

    if params[:tag]
      tag = Tag.find_by_name(params[:tag])
      @topics = tag.topics
    end

    @topics = @topics.includes(:comments, :user, :category, :tags).page(params[:page])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to topics_path
    else
      render :action => :new
    end
  end

  def show
    @comment = Comment.new

    unless cookies["view-topic-#{@topic.id}"]
      cookies["view-topic-#{@topic.id}"] = 'viewed'
      @topic.views_count += 1
      @topic.save!
    end
  end

  def edit
  end

  def update

    @topic.update(topic_params)

    if @topic.save
      redirect_to @topic
    else
      render :action => :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  def subscribe
    @topic.subscriptions.create!(:user => current_user)

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def unsubscribe
    current_user.subscriptions.where(:topic => @topic).destroy_all

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'subscribe' }
    end
  end

  private

  def find_topic
    @topic = Topic.find(params[:id])
  end

  def find_my_topic
    @topic = current_user.topics.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :content, :category_id, :user_id, :image, :tag_list)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def topics_filter(options)
    params.slice(:order, :category, :tag).merge(options)
  end

end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/_form_comment.html.erb
<h2>New Comment</h2>
<%= render partial: 'shared/error_messages', locals: { object: @comment } %>
<%= form_for [@topic, @comment], :id => 'new_comment', :remote => true do |f| %>
<div class="form-group">
  <%= f.label :content %><br>
  <%= f.text_area :content, :class => 'form-control' %>
</div>
<div class="actions">
  <%= f.submit :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/topics/_like.html.erb
<% like = @topic.find_my_like(current_user) %>
<% if like %>
  <%= link_to 'Unlike', topic_like_path(@topic, like), :method => :delete, :remote => true, :class => 'btn btn-default' %>
<% else %>
  <%= link_to 'Like', topic_likes_path(@topic), :method => :post, :remote => true, :class => 'btn btn-default' %>
<% end %>
<% if @topic.likes.any? %>
  <p>Liked by:</p>
  <ul>
    <% @topic.likes.each do |like| %>
      <li><%= like.user.fullname %></li>
    <% end %>
  </ul>
<% end %>

app/views/topics/_subscribe.html.erb
<% if @topic.find_my_subscription(current_user) %>
  <%= link_to 'Unsubscribe', unsubscribe_topic_path(@topic), :method => :delete, :remote => true, :class => 'btn btn-default' %>
<% else %>
  <%= link_to 'Subscribe', subscribe_topic_path(@topic), :method => :post, :remote => true, :class => 'btn btn-default' %>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%= render 'form' %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<div>Sort by
  <%= link_to 'Default', topics_path(topics_filter(:order => "")) %> |
  <%= link_to 'Newest Post', topics_path(topics_filter(:order => 'newest_post')) %> |
  <%= link_to 'Most Replies', topics_path(topics_filter(:order => 'most_replies')) %> |
</div>
<div>Filter by
  <%= link_to 'All', topics_path %> |
  <% Category.all.each do |category| %>
    <%= link_to category.name, topics_path(topics_filter(:category => category.id)) %> |
  <% end %>
</div>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Posted At</th>
    <th>Replies</th>
    <th>Last Replied At</th>
    <th>Views</th>
  </tr>
  <% @topics.each do |topic| %>
    <tr>
      <td>
        <%= link_to topic.title, topic %>
        <%= link_to topic.category.name, topics_path(category: topic.category.id), :class => "label label-default" %>
        <% topic.tags.each do |tag| %>
          <%= link_to tag.name, topics_path(topics_filter(tag: tag.name)), :class => "label label-info" %>
        <% end %>
      </td>
      <td><%= topic.user.try(:fullname) %></td>
      <td><%= topic.created_at.to_s(:short) %></td>
      <td><%= topic.comments.size %></td>
      <td><%= (topic.comments.size > 0 ) ? topic.comments.last.created_at.to_s(:short) : '' %></td>
      <td><%= topic.views_count %></td>
    </tr>
  <% end %>
</table>
<%= paginate @topics %><br>
<%= link_to 'New Topic', new_topic_path, :class => 'btn btn-primary'%>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<p>
  <span class="label label-default"><%= @topic.category.name %></span>
  <span id="like-count" class="label label-default"><%= pluralize(@topic.likes.count, 'Like') %></span>
</p>
<p><%= simple_format @topic.content %></p>
<% if @topic.image.exists? %>
  <p><%= image_tag @topic.image.url(:medium) %></p>
<% end %>
<% if current_user && @topic.user == current_user %>
  <%= link_to 'Edit', edit_topic_path(@topic), :class => 'btn btn-default' %>
  <%= link_to 'Delete', @topic, :method => 'delete', data: { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>
<% end %>
<span id="subscribe-block">
  <%= render 'subscribe' %>
</span>
<span id="like-block">
  <%= render 'like' %>
</span>
<%= render :partial => 'topics/form_comment' %>
<h2>Comments</h2>
<table class="table" id="comment-list">
  <% @topic.comments.each do |comment| %>
    <%= render :partial => 'topic_comments/comment', :locals => { :comment => comment } %>
  <% end %>
</table>

app/views/topics/subscribe.js.erb
$("#subscribe-block").html("<%= j render 'subscribe' %>");