config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :about
  resources :topics do
    resources :comments, :controller => 'topic_comments'
    resources :likes

    member do
      post :subscribe
      delete :unsubscribe
    end
  end

end

app/controllers/topic_comments_controller.rb
class TopicCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_topic

  def create
    @comment = @topic.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private
  def find_topic
    @topic = Topic.find(params[:topic_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/topic_comments_helper.rb
module TopicCommentsHelper
end

app/views/topic_comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td><%= comment.content %></td>
  <td><%= User.find(comment.user_id).fullname %></td>
  <% if current_user && comment.user == current_user %>
  <td><%= link_to 'Delete', topic_comment_path(@topic, comment.id), :method => 'delete', data: { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  <% else %>
  <td />
  <% end %>
</tr>

app/views/topic_comments/create.js.erb
<% if @comment.valid? %>
$("#comment-list").append("<%= j render(:partial => 'comment', :locals => { :comment => @comment }) %>");
$("#new_comment").trigger('reset');
<% else %>
alert("validation failed!");
<% end %>

app/views/topic_comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();